<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="vaibhav-PC" name="Login Test" tests="1" failures="1" timestamp="11 May 2013 16:33:47 GMT" time="0.117" errors="0">
  <testcase name="@AfterTest close" time="0.0" classname="com.qtpselenium.salesforce.testcases.LoginTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at com.qtpselenium.util.Keywords.close(Keywords.java:119)
	at com.qtpselenium.salesforce.testcases.LoginTest.close(LoginTest.java:43)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest close -->
  <testcase name="doLogin" time="0.006" classname="com.qtpselenium.salesforce.testcases.LoginTest">
    <failure type="org.testng.TestNGException" message="
The data provider is trying to pass 1 parameters but the method com.qtpselenium.salesforce.testcases.LoginTest#doLogin takes 4 and TestNG is unable in inject a suitable object">
      <![CDATA[org.testng.TestNGException: 
The data provider is trying to pass 1 parameters but the method com.qtpselenium.salesforce.testcases.LoginTest#doLogin takes 4 and TestNG is unable in inject a suitable object
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
	... 17 more
... Removed 19 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- Login Test -->
